In [1]:
print("EXPLORE ML WEEK 1")

EXPLORE ML WEEK 1


In [2]:
import random
l=[]
for i in range(5):
    l.append(random.randint(1,199))
print("Initial List {}".format(l))
nl=list(map(lambda x:x*3,l))
print("Final List {}".format(nl))

Initial List [23, 183, 31, 168, 163]
Final List [69, 549, 93, 504, 489]


In [3]:
func = lambda a,b:a*b
print("product of 2 and 3 is {}".format(func(2,3)))

product of 2 and 3 is 6


In [5]:
#numpy Examples

In [6]:
height = [1.87,  1.87, 1.82, 1.91, 1.90, 1.85]
weight = [81.65, 97.52, 95.25, 92.98, 86.18, 88.45]

In [8]:
import numpy as np
np_height = np.array(height)
np_weight = np.array(weight)

In [9]:
print(np_height)

[1.87 1.87 1.82 1.91 1.9  1.85]


In [10]:
print(type(np_height))

<class 'numpy.ndarray'>


In [11]:
bmi = np_weight//np_height ** 2

print(bmi)

[23. 27. 28. 25. 23. 25.]


In [13]:
bmi[bmi>=25]

array([27., 28., 25., 25.])